### ISSUE TITLE
No Command Prompt in CEVENCODER folder

### ISSUE THREAD

**Issue by alberth0o0** [Iambian/CEVidium#11]
I downloaded all the folders that is required to convert the videos but when the instructions said to look for a command prompt in the CEVENCODER folder, there were none.

**Comment by Iambian** [comment]
https://www.google.com/search?q=how+to+open+a+command+prompt+from+a+folder

**Comment by alberth0o0** [comment]
I ran into another issue

When I try to convert the video in the command prompt, this shows:
`Loading libraries...
External library file loading
Converting video to target dimensions
Executable 'ffmpeg' not found
An error has occurred during transcoding. Script has terminated.`

**Comment by Iambian** [comment]
Looks like you need to install FFmpeg, as described in the readme's second listed dependency. Try Googling "how to install ffmpeg"
