### ISSUE TITLE
Cannot "make" main program

### ISSUE THREAD

**Issue by CerebralDatabank** [Iambian/CEVidium#3]
I navigated to the CEVPLAY folder, ran the "make" command, and it provides the following error:

```
makefile:33: /include/.makefile: No such file or directory
make: *** No rule to make target `/include/.makefile'.  Stop.
```

P.S. I'm on Windows, and I tried using both Cygwin and gnuwin32.

**Comment by commandz0** [comment]
This error means that the CE Toolchain has not been installed properly.
If you have not installed it yet, releases are available [here](https://github.com/CE-Programming/toolchain/releases).
If the problem persists after installing, ensure that the CEDEV environment variable is set to the path that the toolchain is installed in.

**Comment by CerebralDatabank** [comment]
Thank you, this worked! (I had assumed that the CE Programming Toolchain was simply another name for the on-calc libraries.)
