### ISSUE TITLE
Error Trying to Build the Video Player

### ISSUE THREAD

**Issue by isaacspy** [Iambian/CEVidium#4]
When I input the make command I get an error like this:
`C:\Users\isaac\Documents\calc vid thing\CEVidium-master\CEVPLAY>make
C CE SDK Version 8.6
C:\Users\isaac\Documents\calc vid thing\CEVidium-master\CEVPLAY\src\main.c
C:\USERS\ISAAC\DOCUMENTS\CALC VID THING\CEVIDIUM-MASTER\CEVPLAY\SRC\MAIN.C      (34,9) :        ERROR (217) Cannot open include file "decompress.h"
make: *** [obj/main.src] Error -1`

**Comment by Iambian** [comment]
Cannot reproduce. Try reinstalling the SDK since the file that's being complained about is part of the dev kit.

EDIT: If that fails to fix the problem, post again with the version of the OS you're using and other environment information that could be relevant.

**Comment by isaacspy** [comment]
I tried completely restarting the entire process on a different computer with a different file. Also i used a previous version of the SDK and copied the decompress.h file to it to see if that would fix it. Also i am on Windows 10 I got this error: 
```
C:\Users\isaac\Downloads\CEVidium-master (1)\CEVidium-master\CEVPLAY>make
C CE SDK Version 8.5
C:\Users\isaac\Downloads\CEVidium-master (1)\CEVidium-master\CEVPLAY\src\main.c
C:\USERS\ISAAC\DOWNLOADS\CEVIDIUM-MASTER (1)\CEVIDIUM-MASTER\CEVPLAY\SRC\MAIN.C (37,9) :        ERROR (217) Cannot open include file "gfx/sprites_gfx.h"
make: *** [obj/main.src] Error -1

```

**Comment by ctrefethen** [comment]
@Iambian FYI, we're having this same problem and decompress.h is not included with the windows version of CEDEV and looks like we can possibly get that from a prior version.

However, we also see that gfx/sprites_gfx.h is missing in the CEVPlay repo would you please push that the the repo?

**Comment by ctrefethen** [comment]
@isaacspy So I just commented out the missing .h file and then the various references to the consts from which appear just to affect the titlebar and perhaps some other text and the player did build. It would be nice to get the missing .h file though.

**Comment by Iambian** [comment]
It appears that decompress.h was removed and in its place, compression.h was added. As the call(s) defined in compression.h are incompatible with the code as-is, the relevant function prototype in decompress.h was moved to main.c and the include removed. This seems to work well enough for now.

gfx/sprites_gfx.h is a file that is generated by convpng. Doing `make gfx` before `make` will fix that issue, and the instructions in the readme have been updated to show that.
