### ISSUE TITLE
Video encoder/extern.py broken

### ISSUE THREAD

**Issue by KickingAnimal** [Iambian/CEVidium#9]
when i tried running the batch script it spat some errors out saying print was missint the `()` so I looked at the .py file and it did miss the `()` but then when i added them it failed to load libraries? i installed all dependencies mentioned by the readme.

`  File "[FILEPATH]\CEVidium\CEVENCODER\tools\toolkit2.py", line 1
    print "Loading libraries..."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Loading libraries...")?
`
and after the print fix
`Loading libraries...
Traceback (most recent call last):
  File "[FILEPATH]\CEVidium\CEVENCODER\tools\toolkit2.py", line 2, in <module>
    import sys,os,getopt,Tkinter,struct
ModuleNotFoundError: No module named 'Tkinter'
`

**Comment by KickingAnimal** [comment]
Nevermind it defaulted to python 3.x instead of the unsupported python 2.x and then needed to reinstall pillow module with pip

**Comment by KickingAnimal** [comment]
well I ran into another issue `[FILEPATH]\CEVidium\CEVENCODER>BUILD2.BAT -i FILENAME.mp4 -d -e M2A4 -f
Loading libraries...
External library file loading
Traceback (most recent call last):
  File "tools\toolkit2.py", line 57, in <module>
    settings = extern.Config(extern.STATUSF)
  File "[FILEPATH]\CEVidium\CEVENCODER\tools\extern.py", line 405, in __init__
    self.vname,self.enco,self.titl,self.auth = self.arr
ValueError: need more than 3 values to unpack
`

**Comment by KickingAnimal** [comment]
I also "fixed" it with changing `extern.py` line 405 from `self.vname,self.enco,self.titl,self.auth = self.arr` to `self.vname,self.enco,self.titl = self.arr` and added another line with `self.auth = self.arr`

so from
`self.vname,self.enco,self.titl,self.auth = self.arr`
to
`        self.vname,self.enco,self.titl = self.arr `
`self.auth = self.arr`

**Comment by KickingAnimal** [comment]
my "fix" worked once then it did not anymore

**Comment by KickingAnimal** [comment]
reverted my fix and it works like it should have in the beginning. strange...

**Comment by bartut22** [comment]
> well I ran into another issue `[FILEPATH]\CEVidium\CEVENCODER>BUILD2.BAT -i FILENAME.mp4 -d -e M2A4 -f Loading libraries... External library file loading Traceback (most recent call last): File "tools\toolkit2.py", line 57, in <module> settings = extern.Config(extern.STATUSF) File "[FILEPATH]\CEVidium\CEVENCODER\tools\extern.py", line 405, in __init__ self.vname,self.enco,self.titl,self.auth = self.arr ValueError: need more than 3 values to unpack `

The reason this happens (I think) is because you've already built a video. What worked for me (since I only need 1 video) is to delete the bin and obj folders from CEVENCODER. Doing that will delete the 8xp files that BUILD2 outputs, so back them up or something. I haven't tried the small fix that you showed after though.

**Comment by jlawcg** [comment]
I know this is unrelated to your current issue, but would you be willing to explain how you use ffmpeg to convert a video so that it fits on the calculator? I don't understand how it works and I just want to put Bad Apple on my calculator.

**Comment by KickingAnimal** [comment]
> > well I ran into another issue `[FILEPATH]\CEVidium\CEVENCODER>BUILD2.BAT -i FILENAME.mp4 -d -e M2A4 -f Loading libraries... External library file loading Traceback (most recent call last): File "tools\toolkit2.py", line 57, in <module> settings = extern.Config(extern.STATUSF) File "[FILEPATH]\CEVidium\CEVENCODER\tools\extern.py", line 405, in __init__ self.vname,self.enco,self.titl,self.auth = self.arr ValueError: need more than 3 values to unpack `
> 
> The reason this happens (I think) is because you've already built a video. What worked for me (since I only need 1 video) is to delete the bin and obj folders from CEVENCODER. Doing that will delete the 8xp files that BUILD2 outputs, so back them up or something. I haven't tried the small fix that you showed after though.

This was not the problem. I remember after some time I didn't have any problems anymore. I think I lacked dependencies and used python3 instead of 2

**Comment by KickingAnimal** [comment]
> I know this is unrelated to your current issue, but would you be willing to explain how you use ffmpeg to convert a video so that it fits on the calculator? I don't understand how it works and I just want to put Bad Apple on my calculator.

I build it using build2.bat in windows and the parameters which can be used and explained of you view the help page of build2.bat. I thought it was setting like build2.bat -h for help

**Comment by jlawcg** [comment]
> > I know this is unrelated to your current issue, but would you be willing to explain how you use ffmpeg to convert a video so that it fits on the calculator? I don't understand how it works and I just want to put Bad Apple on my calculator.
> 
> I build it using build2.bat in windows and the parameters which can be used and explained of you view the help page of build2.bat. I thought it was setting like build2.bat -h for help

Do you have to put ffmpeg BUILD2.BAT and then the parameters or is it just supposed to be BUILD2.BAT then parameters? I tried running the command you were using in the BUILD2.BAT file from cmd (with my video filename substituted of course), but it returns absolutely nothing.
`BUILD2.BAT -i FILENAME.mp4 -d -e M2A4 -f`

**Comment by KickingAnimal** [comment]
Just the `BUILD2.BAT` but make sure your CMD is opened in the same directory as the build2 file. Otherwise you should do `cd [your file path]\CEVidium\CEVencoder` where your file path probably starts with `C:` and then the directory where you put CEVidium
Edit: you can I believe also drag and drop the path from the explorer to the CMD so you don't have to type it

**Comment by jlawcg** [comment]
Ok, so I've tried it this way:
`[FILEPATH]\CEVidium-master2\CEVENCODER>C:\[FILEPATH]\CEVidium-master2\CEVENCODER\BUILD2.BAT -i BADAPPLE.mp4 -d -e M2A4 -f`
but it still returns nothing and starts a new line on the same directory in cmd.

Maybe the batch file is broken? Or do I need to reinstall some of the dependencies?

**Comment by KickingAnimal** [comment]
Hey send me a DM on discord that may be faster KickingAnimal#3556

**Comment by jlawcg** [comment]
> Hey send me a DM on discord that may be faster KickingAnimal#3556

Okay. I'll have to DM you later though because I am at school.

**Comment by KickingAnimal** [comment]
Use python 2.x and double check if it uses it.
Other issues are ghost issues, one time it is bad other times it works.
